// Generated by Construct, the game and animation creation tool
// Visit: https://www.construct.net

"use strict";

window._$DOMHandler$_ = class {
    constructor(t, e) {
        this._$_iRuntime$_ = t, this._$_componentId$_ = e, this._$_hasTickCallback$_ = !1, 
        this._$_tickCallback$_ = () => this._$Tick$_();
    }
    _$Attach$_() {}
    _$PostToRuntime$_(t, e, i, s) {
        this._$_iRuntime$_._$PostToRuntimeComponent$_(this._$_componentId$_, t, e, i, s);
    }
    _$PostToRuntimeAsync$_(t, e, i, s) {
        return this._$_iRuntime$_._$PostToRuntimeComponentAsync$_(this._$_componentId$_, t, e, i, s);
    }
    _$_PostToRuntimeMaybeSync$_(t, e, i) {
        this._$_iRuntime$_._$UsesWorker$_() ? this._$PostToRuntime$_(t, e, i) : this._$_iRuntime$_._$_OnLocalRuntimeMessageFromDOM$_({
            type: "event",
            component: this._$_componentId$_,
            handler: t,
            dispatchOpts: i || null,
            data: e,
            responseId: null
        });
    }
    _$AddRuntimeMessageHandler$_(t, e) {
        this._$_iRuntime$_._$AddRuntimeComponentMessageHandler$_(this._$_componentId$_, t, e);
    }
    _$AddRuntimeMessageHandlers$_(t) {
        for (const [e, i] of t) this._$AddRuntimeMessageHandler$_(e, i);
    }
    _$GetRuntimeInterface$_() {
        return this._$_iRuntime$_;
    }
    _$GetComponentID$_() {
        return this._$_componentId$_;
    }
    _$_StartTicking$_() {
        this._$_hasTickCallback$_ || (this._$_iRuntime$_._$_AddRAFCallback$_(this._$_tickCallback$_), 
        this._$_hasTickCallback$_ = !0);
    }
    _$_StopTicking$_() {
        this._$_hasTickCallback$_ && (this._$_iRuntime$_._$_RemoveRAFCallback$_(this._$_tickCallback$_), 
        this._$_hasTickCallback$_ = !1);
    }
    _$Tick$_() {}
}, window._$RateLimiter$_ = class {
    constructor(t, e) {
        this._$_callback$_ = t, this._$_interval$_ = e, this._$_timerId$_ = -1, this._$_lastCallTime$_ = -1 / 0, 
        this._$_timerCallFunc$_ = () => this._$_OnTimer$_(), this._$_ignoreReset$_ = !1, 
        this._$_canRunImmediate$_ = !1;
    }
    _$SetCanRunImmediate$_(t) {
        this._$_canRunImmediate$_ = !!t;
    }
    _$Call$_() {
        if (-1 !== this._$_timerId$_) return;
        const t = Date.now(), e = t - this._$_lastCallTime$_, i = this._$_interval$_;
        e >= i && this._$_canRunImmediate$_ ? (this._$_lastCallTime$_ = t, this._$_RunCallback$_()) : this._$_timerId$_ = self.setTimeout(this._$_timerCallFunc$_, Math.max(i - e, 4));
    }
    _$_RunCallback$_() {
        this._$_ignoreReset$_ = !0, this._$_callback$_(), this._$_ignoreReset$_ = !1;
    }
    _$Reset$_() {
        this._$_ignoreReset$_ || (this._$_CancelTimer$_(), this._$_lastCallTime$_ = Date.now());
    }
    _$_OnTimer$_() {
        this._$_timerId$_ = -1, this._$_lastCallTime$_ = Date.now(), this._$_RunCallback$_();
    }
    _$_CancelTimer$_() {
        -1 !== this._$_timerId$_ && (self.clearTimeout(this._$_timerId$_), this._$_timerId$_ = -1);
    }
    _$Release$_() {
        this._$_CancelTimer$_(), this._$_callback$_ = null, this._$_timerCallFunc$_ = null;
    }
};

{
    class t {
        constructor(t) {
            this._$_elem$_ = t, this._$_hadFirstUpdate$_ = !1, this._$_isVisibleFlag$_ = !0, 
            this._$_wantHtmlIndex$_ = -1, this._$_actualHtmlIndex$_ = -1, this._$_htmlZIndex$_ = -1;
        }
        _$SetVisibleFlag$_(t) {
            this._$_isVisibleFlag$_ = !!t;
        }
        _$GetVisibleFlag$_() {
            return this._$_isVisibleFlag$_;
        }
        _$HadFirstUpdate$_() {
            return this._$_hadFirstUpdate$_;
        }
        _$SetHadFirstUpdate$_() {
            this._$_hadFirstUpdate$_ = !0;
        }
        _$GetWantHTMLIndex$_() {
            return this._$_wantHtmlIndex$_;
        }
        _$SetWantHTMLIndex$_(t) {
            this._$_wantHtmlIndex$_ = t;
        }
        _$GetActualHTMLIndex$_() {
            return this._$_actualHtmlIndex$_;
        }
        _$SetActualHTMLIndex$_(t) {
            this._$_actualHtmlIndex$_ = t;
        }
        _$SetHTMLZIndex$_(t) {
            this._$_htmlZIndex$_ = t;
        }
        _$GetHTMLZIndex$_() {
            return this._$_htmlZIndex$_;
        }
        _$GetElement$_() {
            return this._$_elem$_;
        }
    }
    window._$DOMElementHandler$_ = class extends self._$DOMHandler$_ {
        constructor(t, e) {
            super(t, e), this._$_elementMap$_ = new Map, this._$_autoAttach$_ = !0, this._$AddRuntimeMessageHandlers$_([ [ "create", t => this._$_OnCreate$_(t) ], [ "destroy", t => this._$_OnDestroy$_(t) ], [ "set-visible", t => this._$_OnSetVisible$_(t) ], [ "update-position", t => this._$_OnUpdatePosition$_(t) ], [ "update-state", t => this._$_OnUpdateState$_(t) ], [ "focus", t => this._$_OnSetFocus$_(t) ], [ "set-css-style", t => this._$_OnSetCssStyle$_(t) ], [ "set-attribute", t => this._$_OnSetAttribute$_(t) ], [ "remove-attribute", t => this._$_OnRemoveAttribute$_(t) ] ]), 
            this._$AddDOMElementMessageHandler$_("get-element", t => t);
        }
        _$SetAutoAttach$_(t) {
            this._$_autoAttach$_ = !!t;
        }
        _$AddDOMElementMessageHandler$_(t, e) {
            this._$AddRuntimeMessageHandler$_(t, t => {
                const i = t.elementId, s = this._$GetElementById$_(i);
                return e(s, t);
            });
        }
        _$AddDOMElementMessageHandlers$_(t) {
            for (const [e, i] of t) this._$AddDOMElementMessageHandler$_(e, i);
        }
        _$_OnCreate$_(e) {
            const i = e.elementId, s = this._$CreateElement$_(i, e), n = new t(s);
            this._$_elementMap$_.set(i, n), s.style.boxSizing = "border-box", s.style.display = "none", 
            n._$SetVisibleFlag$_(e.isVisible);
            const o = this._$_GetFocusElement$_(s);
            o.addEventListener("focus", t => this._$_OnFocus$_(i)), o.addEventListener("blur", t => this._$_OnBlur$_(i));
            const r = e.htmlIndex;
            if (n._$SetWantHTMLIndex$_(r), n._$SetHTMLZIndex$_(e.htmlZIndex), this._$_autoAttach$_) {
                const t = this._$GetRuntimeInterface$_()._$GetAvailableHTMLIndex$_(r);
                n._$SetActualHTMLIndex$_(t), this._$GetRuntimeInterface$_()._$GetHTMLWrapElement$_(t).appendChild(s);
            }
        }
        _$CreateElement$_(t, e) {
            throw new Error("required override");
        }
        _$DestroyElement$_(t) {}
        _$_OnDestroy$_(t) {
            const e = t.elementId, i = this._$GetElementById$_(e);
            this._$DestroyElement$_(i), this._$_autoAttach$_ && i.parentElement.removeChild(i), 
            this._$_elementMap$_.delete(e);
        }
        _$PostToRuntimeElement$_(t, e, i) {
            i || (i = {}), i.elementId = e, this._$PostToRuntime$_(t, i);
        }
        _$_PostToRuntimeElementMaybeSync$_(t, e, i) {
            i || (i = {}), i.elementId = e, this._$_PostToRuntimeMaybeSync$_(t, i);
        }
        _$_OnSetVisible$_(t) {
            if (!this._$_autoAttach$_) return;
            const e = this._$_elementMap$_.get(t.elementId), i = e._$GetElement$_();
            e._$HadFirstUpdate$_() ? i.style.display = t.isVisible ? "" : "none" : e._$SetVisibleFlag$_(t.isVisible);
        }
        _$_OnUpdatePosition$_(t) {
            if (!this._$_autoAttach$_) return;
            const e = this._$_elementMap$_.get(t.elementId), i = e._$GetElement$_(), s = this._$GetRuntimeInterface$_();
            i.style.left = t.left + "px", i.style.top = t.top + "px", i.style.width = t.width + "px", 
            i.style.height = t.height + "px";
            const n = t.fontSize;
            null !== n && (i.style.fontSize = n + "em");
            const o = t.htmlIndex;
            e._$SetWantHTMLIndex$_(o);
            const r = s._$GetAvailableHTMLIndex$_(o);
            r !== e._$GetActualHTMLIndex$_() && (i.remove(), s._$GetHTMLWrapElement$_(r).appendChild(i), 
            e._$SetActualHTMLIndex$_(r), s._$_UpdateHTMLElementsZOrder$_());
            const a = t.htmlZIndex;
            a !== e._$GetHTMLZIndex$_() && (e._$SetHTMLZIndex$_(a), s._$_UpdateHTMLElementsZOrder$_()), 
            e._$HadFirstUpdate$_() || (e._$SetHadFirstUpdate$_(), e._$GetVisibleFlag$_() && (i.style.display = ""));
        }
        _$_OnHTMLLayersChanged$_() {
            if (this._$_autoAttach$_) for (const t of this._$_elementMap$_.values()) {
                const e = this._$GetRuntimeInterface$_()._$GetAvailableHTMLIndex$_(t._$GetWantHTMLIndex$_()), i = t._$GetActualHTMLIndex$_();
                if (-1 !== e && -1 !== i && e !== i) {
                    const i = t._$GetElement$_();
                    i.remove(), this._$GetRuntimeInterface$_()._$GetHTMLWrapElement$_(e).appendChild(i), 
                    t._$SetActualHTMLIndex$_(e);
                }
            }
        }
        _$_GetAllElementStatesForZOrderUpdate$_() {
            return this._$_autoAttach$_ ? [ ...this._$_elementMap$_.values() ] : null;
        }
        _$_OnUpdateState$_(t) {
            const e = this._$GetElementById$_(t.elementId);
            this._$UpdateState$_(e, t);
        }
        _$UpdateState$_(t, e) {
            throw new Error("required override");
        }
        _$_GetFocusElement$_(t) {
            return t;
        }
        _$_OnFocus$_(t) {
            this._$PostToRuntimeElement$_("elem-focused", t);
        }
        _$_OnBlur$_(t) {
            this._$PostToRuntimeElement$_("elem-blurred", t);
        }
        _$_OnSetFocus$_(t) {
            const e = this._$_GetFocusElement$_(this._$GetElementById$_(t.elementId));
            t.focus ? e.focus() : e.blur();
        }
        _$_OnSetCssStyle$_(t) {
            const e = this._$GetElementById$_(t.elementId), i = t.prop, s = t.val;
            i.startsWith("--") ? e.style.setProperty(i, s) : e.style[i] = s;
        }
        _$_OnSetAttribute$_(t) {
            this._$GetElementById$_(t.elementId).setAttribute(t.name, t.val);
        }
        _$_OnRemoveAttribute$_(t) {
            this._$GetElementById$_(t.elementId).removeAttribute(t.name);
        }
        _$GetElementById$_(t) {
            const e = this._$_elementMap$_.get(t);
            if (!e) throw new Error(`no element with id ${t}`);
            return e._$GetElement$_();
        }
    };
}

{
    const e = /(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent), i = /android/i.test(navigator.userAgent), s = /safari/i.test(navigator.userAgent) && !/(chrome|chromium|edg\/|OPR\/)/i.test(navigator.userAgent);
    let n = 0;
    function o(t) {
        const e = document.createElement("script");
        return e.async = !1, e.type = "module", t._$isStringSrc$_ ? new Promise(i => {
            const s = "c3_resolve_" + n;
            ++n, self[s] = i, e.textContent = t._$str$_ + `\n\nself["${s}"]();`, document.head.appendChild(e);
        }) : new Promise((i, s) => {
            e.onload = i, e.onerror = s, e.src = t, document.head.appendChild(e);
        });
    }
    async function r() {
        if (!navigator.userActivation || "undefined" == typeof OffscreenCanvas) return !1;
        try {
            let t = !1;
            const e = new Blob([ '\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});' ], {
                type: "text/javascript"
            }), i = new Worker(URL.createObjectURL(e), {
                get type() {
                    t = !0;
                }
            }), s = await new Promise(t => {
                i.addEventListener("message", e => {
                    i.terminate(), t(e.data);
                }), i.postMessage("");
            });
            return t && s;
        } catch (t) {
            return console.warn("Error feature detecting worker mode: ", t), !1;
        }
    }
    let a = new Audio;
    const h = {
        "audio/webm; codecs=opus": !!a.canPlayType("audio/webm; codecs=opus"),
        "audio/ogg; codecs=opus": !!a.canPlayType("audio/ogg; codecs=opus"),
        "audio/webm; codecs=vorbis": !!a.canPlayType("audio/webm; codecs=vorbis"),
        "audio/ogg; codecs=vorbis": !!a.canPlayType("audio/ogg; codecs=vorbis"),
        "audio/mp4": !!a.canPlayType("audio/mp4"),
        "audio/mpeg": !!a.canPlayType("audio/mpeg")
    };
    a = null, window.RealFile = window.File;
    const c = [], l = new Map, d = new Map;
    let u = 0;
    const w = [];
    self.runOnStartup = function(t) {
        if ("function" != typeof t) throw new Error("runOnStartup called without a function");
        w.push(t);
    };
    const m = new Set([ "cordova", "playable-ad-single-file", "playable-ad-zip", "instant-games" ]);
    function p(t) {
        return m.has(t);
    }
    let f = !1;
    window._$RuntimeInterface$_ = class t {
        #t=!0;
        #e=null;
        #i="";
        #s="";
        #n=null;
        #o=null;
        #r=[];
        #a=null;
        #h=!0;
        #c=[];
        #l=[];
        #d=!1;
        #u=() => this.#w();
        #m=!1;
        #p=0;
        #f=null;
        #v=-1;
        #g=() => this.#y();
        #b=new Set;
        #k=null;
        #S=[];
        #_=[];
        #x=new Map;
        #O="";
        constructor(t) {
            if (this.#t = t._$useWorker$_, this.#s = t._$scriptFolder$_, this.#O = t._$exportType$_, 
            "playable-ad-single-file" !== this.#O && "playable-ad-zip" !== this.#O && "instant-games" !== this.#O || (this.#t = !1), 
            (s || "macos-wkwebview" === this.#O) && (this.#t = !1), "cordova" === this.#O && this.#t && i) {
                const t = /Chrome\/(\d+)/i.exec(navigator.userAgent);
                t && parseInt(t[1], 10) >= 90 || (this.#t = !1);
            }
            this._$IsAnyWebView2Wrapper$_() ? self.chrome.webview.addEventListener("message", t => this.#M(t.data, t.additionalObjects)) : "macos-wkwebview" === this.#O ? self.C3WrapperOnMessage = t => this.#M(JSON.parse(t)) : "linux-cef" === this.#O && self.c3_linux_cef_set_message_callback(t => this.#M(JSON.parse(t))), 
            this._$_localFileBlobs$_ = null, this._$_localFileStrings$_ = null, "html5" !== this.#O || window.isSecureContext || console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available."), 
            this._$AddRuntimeComponentMessageHandler$_("canvas", "update-size", t => this.#E(t)), 
            this._$AddRuntimeComponentMessageHandler$_("canvas", "set-html-layer-count", t => this._OnSetHTMLLayerCount(t)), 
            this._$AddRuntimeComponentMessageHandler$_("canvas", "cleanup-html-layers", () => this.#I()), 
            this._$AddRuntimeComponentMessageHandler$_("canvas", "update-html-layer-dom-state", t => this.#P(t.layersDomState)), 
            this._$AddRuntimeComponentMessageHandler$_("runtime", "create-job-worker", t => this.#T(t)), 
            this._$AddRuntimeComponentMessageHandler$_("runtime", "send-wrapper-extension-message", t => this.#R(t)), 
            this._$AddRuntimeComponentMessageHandler$_("runtime", "send-raw-wrapper-extension-message", t => this.#C(t)), 
            "cordova" === this.#O ? document.addEventListener("deviceready", () => this.#W(t)) : this.#W(t), 
            this._$_skipAndroidVirtualKeyboardDetection$_ = 0;
        }
        _$Release$_() {
            this._$_CancelAnimationFrame$_(), this.#e && (this.#e.onmessage = null, this.#e = null), 
            this.#n && (this.#n.terminate(), this.#n = null), this.#o && (this.#o._$Release$_(), 
            this.#o = null);
            for (const {canvas: t, _$htmlWrap$_: e} of this.#c) t.remove(), e.remove();
            this.#c.length = 0;
        }
        _$GetMainCanvas$_() {
            return this.#c[0].canvas;
        }
        _$GetAvailableHTMLIndex$_(t) {
            return Math.min(t, this.#c.length - 1);
        }
        _$GetHTMLWrapElement$_(t) {
            if (t < 0 || t >= this.#c.length) throw new RangeError("invalid canvas layer");
            return this.#c[t]._$htmlWrap$_;
        }
        _GetHTMLWrapElement(t) {
            return this._$GetHTMLWrapElement$_(t);
        }
        _$GetRuntimeBaseURL$_() {
            return this.#i;
        }
        _$UsesWorker$_() {
            return this.#t;
        }
        _$GetExportType$_() {
            return this.#O;
        }
        _$GetScriptFolder$_() {
            return this.#s;
        }
        _$IsiOSCordova$_() {
            return e && "cordova" === this.#O;
        }
        _$IsiOSWebView$_() {
            const t = navigator.userAgent;
            return e && p(this.#O) || navigator.standalone || /crios\/|fxios\/|edgios\//i.test(t);
        }
        _$IsAndroid$_() {
            return i;
        }
        _$IsAndroidWebView$_() {
            return i && p(this.#O);
        }
        _$IsWindowsWebView2$_() {
            return "windows-webview2" === this.#O || !!("preview" === this.#O && window.chrome && window.chrome.webview && window.chrome.webview.postMessage);
        }
        _$IsAnyWebView2Wrapper$_() {
            return this._$IsWindowsWebView2$_() || "xbox-uwp-webview2" === this.#O;
        }
        _$SkipNextAndroidVirtualKeyboardDetection$_() {
            this._$IsAndroidWebView$_() && this._$_skipAndroidVirtualKeyboardDetection$_++;
        }
        _$CanDoAndroidVirtualKeyboardDetection$_() {
            return this._$_CanDoAndroidVirtualKeyboardDetection$_().next().value;
        }
        * _$_CanDoAndroidVirtualKeyboardDetection$_() {
            if (!this._$IsAndroidWebView$_()) return !0;
            yield 0 === this._$_skipAndroidVirtualKeyboardDetection$_, this._$_skipAndroidVirtualKeyboardDetection$_ > 0 && this._$_skipAndroidVirtualKeyboardDetection$_--;
        }
        async #W(t) {
            if (this.#t && (await r() || (this.#t = !1)), "macos-wkwebview" === this.#O && this._$_SendWrapperMessage$_({
                type: "ready"
            }), this._$IsAnyWebView2Wrapper$_() || "macos-wkwebview" === this.#O || "linux-cef" === this.#O) {
                this.#A();
                const t = await this.#F();
                this.#S = t.registeredComponentIds;
            }
            if ("playable-ad-single-file" === this.#O && (this._$_localFileBlobs$_ = self.c3_base64files, 
            this._$_localFileStrings$_ = {}, await this.#D()), t._$runtimeBaseUrl$_) this.#i = t._$runtimeBaseUrl$_; else {
                const t = location.origin;
                this.#i = ("null" === t ? "file:///" : t) + location.pathname;
                const e = this.#i.lastIndexOf("/");
                -1 !== e && (this.#i = this.#i.substr(0, e + 1));
            }
            const e = new MessageChannel;
            if (this.#e = e.port1, this.#e.onmessage = t => this._OnMessageFromRuntime(t.data), 
            window.c3_addPortMessageHandler && window.c3_addPortMessageHandler(t => this.#H(t)), 
            this.#f = new self._$JobSchedulerDOM$_(this), await this.#f._$Init$_(), "object" == typeof window.StatusBar && window.StatusBar.hide(), 
            "object" == typeof window.AndroidFullScreen) try {
                await new Promise((t, e) => {
                    window.AndroidFullScreen.immersiveMode(t, e);
                });
            } catch (t) {
                console.error("Failed to enter Android immersive mode: ", t);
            }
            this.#t ? await this.#L(t, e.port2) : await this.#U(t, e.port2);
        }
        #G(e) {
            return {
                runtimeBaseUrl: this.#i,
                previewUrl: location.href,
                windowInnerWidth: this._$_GetWindowInnerWidth$_(),
                windowInnerHeight: this._$_GetWindowInnerHeight$_(),
                cssDisplayMode: this._$GetCssDisplayMode$_(),
                devicePixelRatio: window.devicePixelRatio,
                isFullscreen: t._$IsDocumentFullscreen$_(),
                swClientId: window.cr_swClientId || "",
                exportType: e._$exportType$_,
                fileMap: globalThis._$c3_swFileMap$_ ?? new Map(Object.entries(this._$_localFileBlobs$_ ?? {})),
                scriptFolder: this.#s,
                isDebug: new URLSearchParams(self.location.search).has("debug"),
                ife: !!self._$ife$_,
                jobScheduler: this.#f._$GetPortData$_(),
                supportedAudioFormats: h,
                isiOSCordova: this._$IsiOSCordova$_(),
                isiOSWebView: this._$IsiOSWebView$_(),
                isWindowsWebView2: this._$IsWindowsWebView2$_(),
                isAnyWebView2Wrapper: this._$IsAnyWebView2Wrapper$_(),
                wrapperComponentIds: this.#S,
                isFBInstantAvailable: void 0 !== self.FBInstant
            };
        }
        async #L(t, e) {
            const i = t._$workerMainUrl$_;
            "preview" === this.#O ? (this.#n = new Worker("previewworker.js", {
                type: "module",
                name: "Runtime"
            }), await new Promise((t, e) => {
                const s = i => {
                    this.#n.removeEventListener("message", s), i.data && "ok" === i.data.type ? t() : e();
                };
                this.#n.addEventListener("message", s), this.#n.postMessage({
                    type: "construct-worker-init",
                    import: new URL(i, this.#i).toString()
                });
            })) : this.#n = await this._$CreateWorker$_(i, {
                type: "module",
                name: "Runtime"
            });
            const s = document.createElement("canvas");
            s.style.display = "none";
            const n = s.transferControlToOffscreen();
            document.body.appendChild(s);
            const o = document.createElement("div");
            o.className = "c3htmlwrap", o.setAttribute("interactive", ""), document.body.appendChild(o), 
            this.#c.push({
                canvas: s,
                _$htmlWrap$_: o,
                _$lastHtmlLayerDomState$_: {
                    isVisible: !0,
                    opacity: 1,
                    _$isInteractive$_: !0
                }
            }), window.c3canvas = s, self.C3_InsertHTMLPlaceholders && self.C3_InsertHTMLPlaceholders(), 
            this.#n.postMessage(Object.assign(this.#G(t), {
                type: "init-runtime",
                isInWorker: !0,
                messagePort: e,
                canvas: n,
                runtimeMainScript: t._$runtimeMainScript$_,
                projectMainScriptPath: t._$projectMainScriptPath$_,
                javaScriptInEventsPath: t._$javaScriptInEventsPath$_,
                typeScriptInEventsPath: t._$typeScriptInEventsPath$_
            }), [ e, n, ...this.#f._$GetPortTransferables$_() ]), this.#r = c.map(t => new t(this)), 
            this.#V(), this.#a._$_AddDefaultCanvasEventHandlers$_(s), this.#a._$_AddDefaultHTMLWrapEventHandlers$_(o), 
            this.#a._$_EnableWindowResizeEvent$_(), self.c3_callFunction = (t, e) => this.#a._$_InvokeFunctionFromJS$_(t, e), 
            "preview" === this.#O && (self.goToLastErrorScript = () => this._$PostToRuntimeComponent$_("runtime", "go-to-last-error-script"));
        }
        async #U(t, e) {
            const i = document.createElement("canvas");
            i.style.display = "none", document.body.appendChild(i);
            const s = document.createElement("div");
            s.className = "c3htmlwrap", s.setAttribute("interactive", ""), document.body.appendChild(s), 
            this.#c.push({
                canvas: i,
                _$htmlWrap$_: s,
                _$lastHtmlLayerDomState$_: {
                    isVisible: !0,
                    opacity: 1,
                    _$isInteractive$_: !0
                }
            }), window.c3canvas = i, self.C3_InsertHTMLPlaceholders && self.C3_InsertHTMLPlaceholders(), 
            this.#r = c.map(t => new t(this)), this.#V(), this.#a._$_AddDefaultCanvasEventHandlers$_(i), 
            this.#a._$_AddDefaultHTMLWrapEventHandlers$_(s);
            const n = await this.#j(t._$runtimeMainScript$_);
            let r, a;
            globalThis.C3_SetInitFunctions = (t, e) => {
                r = t, a = e, globalThis.C3_SetInitFunctions = null;
            }, await o(n);
            const h = t._$projectMainScriptPath$_, l = t._$javaScriptInEventsPath$_, d = t._$typeScriptInEventsPath$_;
            if (h) try {
                if (await o(h), "preview" === this.#O && !globalThis._$C3_ProjectMainScriptOK$_) throw new Error("main script did not run to completion");
            } catch (t) {
                this.#z(), console.error("Error loading project main script: ", t), alert(`Failed to load the project main script (${h}). Check all your JavaScript code has valid syntax, all imports are written correctly, and that an exception was not thrown running the script. Press F12 and check the console for error details.`);
            }
            if (l) try {
                if (await o(l), "preview" === this.#O && !globalThis._$C3$_._$JavaScriptInEvents$_) throw new Error("JavaScript in events did not run to completion");
            } catch (t) {
                this.#z(), console.error("Error loading JavaScript in events: ", t), alert("Failed to load JavaScript in events. Check all your JavaScript code has valid syntax, all imports are written correctly, and that an exception was not thrown running the 'Imports for events' script. Press F12 and check the console for error details.");
            }
            if (d) try {
                if (await o(d), "preview" === this.#O && !globalThis._$C3$_._$TypeScriptInEvents$_) throw new Error("TypeScript in events did not run to completion");
            } catch (t) {
                this.#z(), console.error("Error loading TypeScript in events: ", t), alert("Failed to load TypeScript in events. Check all your TypeScript code has valid syntax, all imports are written correctly, and that an exception was not thrown running the 'Imports for events' script. Press F12 and check the console for error details.");
            }
            const u = Object.assign(this.#G(t), {
                isInWorker: !1,
                messagePort: e,
                canvas: i,
                runOnStartupFunctions: w
            });
            this.#a._$_EnableWindowResizeEvent$_(), this.#$(), this.#o = r(u), await a(this.#o, u);
        }
        async _$CreateWorker$_(t, e) {
            if (t.startsWith("blob:")) return new Worker(t, e);
            if ("playable-ad-single-file" === this.#O) {
                const i = this._$_localFileBlobs$_[t];
                if (!i) throw new Error("missing script: " + t);
                return new Worker(URL.createObjectURL(i), e);
            }
            const i = new URL(t, location.href);
            if (location.origin !== i.origin) {
                const t = await fetch(i);
                if (!t.ok) throw new Error("failed to fetch worker script");
                const s = await t.blob();
                return new Worker(URL.createObjectURL(s), e);
            }
            return new Worker(i, e);
        }
        _$_GetWindowInnerWidth$_() {
            return Math.max(window.innerWidth, 1);
        }
        _$_GetWindowInnerHeight$_() {
            return Math.max(window.innerHeight, 1);
        }
        _$GetCssDisplayMode$_() {
            if (this._$IsAnyWebView2Wrapper$_()) return "standalone";
            const t = this._$GetExportType$_();
            return new Set([ "cordova", "macos-wkwebview", "linux-cef" ]).has(t) ? "standalone" : window.matchMedia("(display-mode: fullscreen)").matches ? "fullscreen" : window.matchMedia("(display-mode: standalone)").matches ? "standalone" : window.matchMedia("(display-mode: minimal-ui)").matches ? "minimal-ui" : navigator.standalone ? "standalone" : "browser";
        }
        #$() {
            this.#z();
        }
        #z() {
            const t = window.cr_previewLoadingElem;
            t && (t.parentElement.removeChild(t), window.cr_previewLoadingElem = null);
        }
        async #T(t) {
            const e = await this.#f._$_CreateJobWorker$_();
            return {
                outputPort: e,
                transferables: [ e ]
            };
        }
        #E(t) {
            if (this._$IsExportingToVideo$_()) return;
            const e = t.styleWidth + "px", i = t.styleHeight + "px", s = t.marginLeft + "px", n = t.marginTop + "px";
            for (const {canvas: t, _$htmlWrap$_: o} of this.#c) t.style.width = e, t.style.height = i, 
            t.style.marginLeft = s, t.style.marginTop = n, o.style.width = e, o.style.height = i, 
            o.style.marginLeft = s, o.style.marginTop = n, this.#h && (t.style.display = "", 
            o.style.display = "");
            document.documentElement.style.setProperty("--construct-scale", t.displayScale), 
            this.#h = !1;
        }
        _OnSetHTMLLayerCount(t) {
            const e = t.count, i = t.layersDomState, s = t.immediate, n = t.styleWidth + "px", o = t.styleHeight + "px", r = t.marginLeft + "px", a = t.marginTop + "px", h = [], c = [];
            if (e < this.#c.length) for (;this.#c.length > e; ) {
                const {canvas: t, _$htmlWrap$_: e} = this.#c.pop();
                e.remove(), this.#t && !s ? this.#l.push(t) : t.remove();
            } else if (e > this.#c.length) for (let t = 0, i = e - this.#c.length; t < i; ++t) {
                const t = document.createElement("canvas");
                if (t.classList.add("c3overlay"), this.#t) {
                    const e = t.transferControlToOffscreen();
                    h.push(e), c.push(e);
                } else h.push(t);
                document.body.appendChild(t);
                const e = document.createElement("div");
                e.classList.add("c3htmlwrap", "c3overlay"), e.setAttribute("interactive", ""), document.body.appendChild(e), 
                t.style.width = n, t.style.height = o, t.style.marginLeft = r, t.style.marginTop = a, 
                e.style.width = n, e.style.height = o, e.style.marginLeft = r, e.style.marginTop = a, 
                this.#a._$_AddDefaultCanvasEventHandlers$_(t), this.#a._$_AddDefaultHTMLWrapEventHandlers$_(e), 
                this.#c.push({
                    canvas: t,
                    _$htmlWrap$_: e,
                    _$lastHtmlLayerDomState$_: {
                        isVisible: !0,
                        opacity: 1,
                        _$isInteractive$_: !0
                    }
                });
            }
            this.#P(i);
            for (const t of this.#r) t instanceof window._$DOMElementHandler$_ && t._$_OnHTMLLayersChanged$_();
            return this._$_UpdateHTMLElementsZOrder$_(), {
                addedCanvases: h,
                transferables: c
            };
        }
        #P(t) {
            for (let e = 0, i = Math.min(this.#c.length, t.length); e < i; ++e) {
                const {_$htmlWrap$_: i, _$lastHtmlLayerDomState$_: s} = this.#c[e], n = t[e], o = n.isVisible, r = n.opacity, a = n.isInteractive;
                o !== s.isVisible && (i.style.display = o ? "" : "none", s.isVisible = o), r !== s.opacity && (i.style.opacity = 1 === r ? "" : String(r), 
                s.opacity = r), a !== s._$isInteractive$_ && (i.style.pointerEvents = a ? "" : "none", 
                a ? i.setAttribute("interactive", "") : i.removeAttribute("interactive"), s._$isInteractive$_ = a);
            }
        }
        #I() {
            for (const t of this.#l) t.remove();
            this.#l.length = 0;
        }
        _$_UpdateHTMLElementsZOrder$_() {
            this.#d || (this.#d = !0, this._$_AddRAFCallback$_(this.#u));
        }
        #w() {
            this._$_RemoveRAFCallback$_(this.#u), this.#d = !1;
            let t = [];
            for (const e of this.#r) if (e instanceof window._$DOMElementHandler$_) {
                const i = e._$_GetAllElementStatesForZOrderUpdate$_();
                i && t.push(...i);
            }
            t.sort((t, e) => {
                const i = t._$GetActualHTMLIndex$_(), s = e._$GetActualHTMLIndex$_();
                return i !== s ? i - s : t._$GetHTMLZIndex$_() - e._$GetHTMLZIndex$_();
            });
            let e = 0, i = 0, s = 0, n = t.length;
            for (;s < n; ++s) {
                const n = t[s];
                n._$GetActualHTMLIndex$_() !== e && (this.#B(e, t.slice(i, s)), e = n._$GetActualHTMLIndex$_(), 
                i = s);
            }
            i < s && this.#B(e, t.slice(i, s));
        }
        #B(t, e) {
            if (e.length <= 1) return;
            if (t >= this.#c.length) return;
            const i = e.map(t => t._$GetElement$_()), s = new Set(i), n = this._$GetHTMLWrapElement$_(t), o = Array.from(n.children).filter(t => s.has(t));
            for (let t = 0, e = 0, s = i.length; t < s; ++t) {
                const s = i[t], r = o[e];
                s === r ? ++e : n.moveBefore ? n.moveBefore(s, r) : n.insertBefore(s, r);
            }
        }
        _$_OnLocalRuntimeMessageFromDOM$_(t) {
            if (this.#t) throw new Error("not available in worker mode");
            this.#o._OnMessageFromDOM(t);
        }
        _$PostToRuntimeComponent$_(t, e, i, s, n) {
            this.#e.postMessage({
                type: "event",
                component: t,
                handler: e,
                dispatchOpts: s || null,
                data: i,
                responseId: null
            }, n);
        }
        _$PostToRuntimeComponentAsync$_(t, e, i, s, n) {
            const o = u++, r = new Promise((t, e) => {
                d.set(o, {
                    resolve: t,
                    reject: e
                });
            });
            return this.#e.postMessage({
                type: "event",
                component: t,
                handler: e,
                dispatchOpts: s || null,
                data: i,
                responseId: o
            }, n), r;
        }
        _OnMessageFromRuntime(t) {
            const e = t.type;
            if ("event" === e) return this.#Y(t);
            if ("result" === e) this.#X(t); else if ("runtime-ready" === e) this.#J(); else if ("alert-error" === e) this.#z(), 
            alert(t.message); else {
                if ("creating-runtime" !== e) throw new Error(`unknown message '${e}'`);
                this.#$();
            }
        }
        #Y(t) {
            const e = t.component, i = t.handler, s = t.data, n = t.responseId, o = l.get(e);
            if (!o) return void console.warn(`[DOM] No event handlers for component '${e}'`);
            const r = o.get(i);
            if (!r) return void console.warn(`[DOM] No handler '${i}' for component '${e}'`);
            let a = null;
            try {
                a = r(s);
            } catch (t) {
                return console.error(`Exception in '${e}' handler '${i}':`, t), void (null !== n && this.#K(n, !1, "" + t));
            }
            if (null === n) return a;
            a && a.then ? a.then(t => this.#K(n, !0, t)).catch(t => {
                console.error(`Rejection from '${e}' handler '${i}':`, t), this.#K(n, !1, "" + t);
            }) : this.#K(n, !0, a);
        }
        #K(t, e, i) {
            let s;
            i && i.transferables && (s = i.transferables), this.#e.postMessage({
                type: "result",
                responseId: t,
                isOk: e,
                result: i
            }, s);
        }
        #X(t) {
            const e = t.responseId, i = t.isOk, s = t.result, n = d.get(e);
            i ? n.resolve(s) : n.reject(s), d.delete(e);
        }
        _$AddRuntimeComponentMessageHandler$_(t, e, i) {
            let s = l.get(t);
            if (s || (s = new Map, l.set(t, s)), s.has(e)) throw new Error(`[DOM] Component '${t}' already has handler '${e}'`);
            s.set(e, i);
        }
        static _$AddDOMHandlerClass$_(t) {
            if (c.includes(t)) throw new Error("DOM handler already added");
            c.push(t);
        }
        #V() {
            for (const t of this.#r) if ("runtime" === t._$GetComponentID$_()) return void (this.#a = t);
            throw new Error("cannot find runtime DOM handler");
        }
        #H(t) {
            this._$PostToRuntimeComponent$_("debugger", "message", t);
        }
        #J() {
            for (const t of this.#r) t._$Attach$_();
        }
        static _$IsDocumentFullscreen$_() {
            return !!(document.fullscreenElement || document.webkitFullscreenElement || document.mozFullScreenElement || f);
        }
        static _$_SetWrapperIsFullscreenFlag$_(t) {
            f = !!t;
        }
        async _$GetRemotePreviewStatusInfo$_() {
            return await this._$PostToRuntimeComponentAsync$_("runtime", "get-remote-preview-status-info");
        }
        _$_AddRAFCallback$_(t) {
            this.#b.add(t), this._$_RequestAnimationFrame$_();
        }
        _$_RemoveRAFCallback$_(t) {
            this.#b.delete(t), 0 === this.#b.size && this._$_CancelAnimationFrame$_();
        }
        _$_RequestAnimationFrame$_() {
            -1 === this.#v && this.#b.size > 0 && (this.#v = requestAnimationFrame(this.#g));
        }
        _$_CancelAnimationFrame$_() {
            -1 !== this.#v && (cancelAnimationFrame(this.#v), this.#v = -1);
        }
        #y() {
            this.#v = -1;
            for (const t of this.#b) t();
            this._$_RequestAnimationFrame$_();
        }
        _$TryPlayMedia$_(t) {
            this.#a._$TryPlayMedia$_(t);
        }
        _$RemovePendingPlay$_(t) {
            this.#a._$RemovePendingPlay$_(t);
        }
        _$_PlayPendingMedia$_() {
            this.#a._$_PlayPendingMedia$_();
        }
        _$AddAnyGamepadInputCallback$_(t) {
            this.#a._$_AddAnyGamepadInputCallback$_(t);
        }
        _$RemoveAnyGamepadInputCallback$_(t) {
            this.#a._$_RemoveAnyGamepadInputCallback$_(t);
        }
        _$SetSilent$_(t) {
            this.#a._$SetSilent$_(t);
        }
        _$IsAudioFormatSupported$_(t) {
            return !!h[t];
        }
        _$SetIsExportingToVideo$_(t) {
            this.#m = !0, this.#p = t;
        }
        _$IsExportingToVideo$_() {
            return this.#m;
        }
        _$GetExportToVideoDuration$_() {
            return this.#p;
        }
        _$IsAbsoluteURL$_(t) {
            return /^(?:[a-z\-]+:)?\/\//.test(t) || "data:" === t.substr(0, 5) || "blob:" === t.substr(0, 5);
        }
        _$IsRelativeURL$_(t) {
            return !this._$IsAbsoluteURL$_(t);
        }
        async #j(t) {
            if ("playable-ad-single-file" === this.#O) {
                if (this._$_localFileStrings$_.hasOwnProperty(t)) return {
                    _$isStringSrc$_: !0,
                    _$str$_: this._$_localFileStrings$_[t]
                };
                if (this._$_localFileBlobs$_.hasOwnProperty(t)) return URL.createObjectURL(this._$_localFileBlobs$_[t]);
                throw new Error("missing script: " + t);
            }
            return t;
        }
        _PlayableAdFetchBlob(t) {
            if (this._$_localFileBlobs$_.hasOwnProperty(t)) return this._$_localFileBlobs$_[t];
            throw new Error("missing file: " + t);
        }
        #q() {
            const t = window.cordova && window.cordova.plugins && window.cordova.plugins.permissions;
            if ("object" != typeof t) throw new Error("Permission API is not loaded");
            return t;
        }
        #N(t, e) {
            const i = t[e];
            if ("string" != typeof i) throw new Error("Invalid permission name");
            return i;
        }
        #Z(t) {
            const e = this.#q();
            return new Promise((i, s) => e.checkPermission(this.#N(e, t), t => i(!!t.hasPermission), s));
        }
        #Q(t) {
            const e = this.#q();
            return new Promise((i, s) => e.requestPermission(this.#N(e, t), t => i(!!t.hasPermission), s));
        }
        async _$RequestPermissions$_(t) {
            if ("cordova" !== this._$GetExportType$_()) return !0;
            if (this._$IsiOSCordova$_()) return !0;
            for (const e of t) if (!await this.#Z(e) && !1 === await this.#Q(e)) return !1;
            return !0;
        }
        async _$RequirePermissions$_(...t) {
            if (!1 === await this._$RequestPermissions$_(t)) throw new Error("Permission not granted");
        }
        #M(e, i) {
            if ("object" != typeof e || !e) return void console.warn("Unknown wrapper message: ", e);
            const s = e.type;
            if ("directory-handles" === s) this.#_ = i; else if ("wrapper-init-response" === s) this.#k(e), 
            this.#k = null; else if ("fullscreen-change" === s) t._$_SetWrapperIsFullscreenFlag$_(e.isFullscreen), 
            this.#a._$_OnFullscreenChange$_(); else if ("log-to-console" === s) switch (e.logType) {
              case "error":
                console.error(e.message);
                break;

              case "warning":
                console.warn(e.message);
                break;

              default:
                console.log(e.message);
            } else if ("window-maximized" == s || "window-minimized" == s) {
                const t = {
                    "window-maximized": "windowmaximize",
                    "window-minimized": "windowminimize"
                };
                this._$PostToRuntimeComponent$_("runtime", t[s], null, {
                    dispatchRuntimeEvent: !0,
                    dispatchUserScriptEvent: !0
                });
            } else if ("extension-message" === s) this._$PostToRuntimeComponent$_("runtime", "wrapper-extension-message", e); else {
                const t = this.#x.get(s);
                t ? t(e) : console.warn("Unknown wrapper message: ", e);
            }
        }
        _$_AddWrapperMessageHandler$_(t, e) {
            this.#x.set(t, e);
        }
        #R(t) {
            this._$_SendWrapperMessage$_({
                type: "extension-message",
                componentId: t.componentId,
                messageId: t.messageId,
                params: t.params || [],
                asyncId: t.asyncId
            });
        }
        #C(t) {
            this._$_SendWrapperMessage$_(t);
        }
        _$_SendWrapperMessage$_(t) {
            this._$IsAnyWebView2Wrapper$_() ? window.chrome.webview.postMessage(JSON.stringify(t)) : "macos-wkwebview" === this.#O ? window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(t)) : "linux-cef" === this.#O && window.c3_linux_cef_sendmessage(JSON.stringify(t));
        }
        #A() {
            window.moveTo = (t, e) => {
                this._$_SendWrapperMessage$_({
                    type: "set-window-position",
                    windowX: Math.ceil(t),
                    windowY: Math.ceil(e)
                });
            }, window.resizeTo = (t, e) => {
                this._$_SendWrapperMessage$_({
                    type: "set-window-size",
                    windowWidth: Math.ceil(t),
                    windowHeight: Math.ceil(e)
                });
            }, window.focus = () => {
                this._$_SendWrapperMessage$_({
                    type: "focus-window"
                });
            };
        }
        #F() {
            return new Promise(t => {
                this.#k = t, this._$_SendWrapperMessage$_({
                    type: "wrapper-init"
                });
            });
        }
        _$_GetDirectoryHandles$_() {
            return this.#_;
        }
        async #D() {
            const t = [];
            for (const [e, i] of Object.entries(this._$_localFileBlobs$_)) t.push(this.#tt(e, i));
            await Promise.all(t);
        }
        async #tt(t, e) {
            if ("object" == typeof e) this._$_localFileBlobs$_[t] = new Blob([ e.str ], {
                type: e.type
            }), this._$_localFileStrings$_[t] = e.str; else {
                let i = await this.#et(e);
                i || (i = this.#it(e)), this._$_localFileBlobs$_[t] = i;
            }
        }
        async #et(t) {
            try {
                const e = await fetch(t);
                return await e.blob();
            } catch (t) {
                return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.", t), 
                null;
            }
        }
        #it(t) {
            const e = this.#st(t);
            return this.#nt(e.data, e._$mime_type$_);
        }
        #st(t) {
            const e = t.indexOf(",");
            if (e < 0) throw new URIError("expected comma in data: uri");
            const i = t.substring(5, e), s = t.substring(e + 1), n = i.split(";"), o = n[0] || "", r = n[1], a = n[2];
            let h;
            return h = "base64" === r || "base64" === a ? atob(s) : decodeURIComponent(s), {
                _$mime_type$_: o,
                data: h
            };
        }
        #nt(t, e) {
            let i, s, n = t.length, o = n >> 2, r = new Uint8Array(n), a = new Uint32Array(r.buffer, 0, o);
            for (i = 0, s = 0; i < o; ++i) a[i] = t.charCodeAt(s++) | t.charCodeAt(s++) << 8 | t.charCodeAt(s++) << 16 | t.charCodeAt(s++) << 24;
            let h = 3 & n;
            for (;h--; ) r[s] = t.charCodeAt(s), ++s;
            return new Blob([ r ], {
                type: e
            });
        }
    };
}

{
    const v = self._$RuntimeInterface$_;
    function g(t) {
        return t.sourceCapabilities && t.sourceCapabilities.firesTouchEvents || t.originalEvent && t.originalEvent.sourceCapabilities && t.originalEvent.sourceCapabilities.firesTouchEvents;
    }
    /firefox/i.test(navigator.userAgent);
    const y = new Map([ [ "OSLeft", "MetaLeft" ], [ "OSRight", "MetaRight" ] ]), b = {
        dispatchRuntimeEvent: !0,
        dispatchUserScriptEvent: !0
    }, k = {
        dispatchUserScriptEvent: !0
    }, S = {
        dispatchRuntimeEvent: !0
    };
    async function _(t) {
        const e = URL.createObjectURL(t);
        try {
            return await (i = e, new Promise((t, e) => {
                const s = new Image;
                s.onload = () => t(s), s.onerror = t => e(t), s.src = i;
            }));
        } finally {
            URL.revokeObjectURL(e);
        }
        var i;
    }
    function x(t) {
        do {
            if (t.parentNode && t.hasAttribute("contenteditable")) return !0;
            t = t.parentNode;
        } while (t);
        return !1;
    }
    const O = new Set([ "input", "textarea", "datalist", "select" ]), M = new Set([ "canvas", "body", "html" ]);
    function E(t) {
        if (!t.target.tagName) return;
        const e = t.target.tagName.toLowerCase();
        M.has(e) && t.preventDefault();
    }
    function I(t) {
        t.target.tagName && t.target.classList.contains("c3htmlwrap") && t.preventDefault();
    }
    function P(t) {
        (t.metaKey || t.ctrlKey) && t.preventDefault();
    }
    self.C3_GetSvgImageSize = async function(t) {
        const e = await _(t);
        if (e.width > 0 && e.height > 0) return [ e.width, e.height ];
        {
            e.style.position = "absolute", e.style.left = "0px", e.style.top = "0px", e.style.visibility = "hidden", 
            document.body.appendChild(e);
            const t = e.getBoundingClientRect();
            return document.body.removeChild(e), [ t.width, t.height ];
        }
    }, self.C3_RasterSvgImageBlob = async function(t, e, i, s, n) {
        const o = await _(t), r = document.createElement("canvas");
        return r.width = s, r.height = n, r.getContext("2d").drawImage(o, 0, 0, e, i), r;
    };
    let T = !1;
    function R() {
        try {
            return window.parent && window.parent.document.hasFocus();
        } catch (t) {
            return !1;
        }
    }
    document.addEventListener("pause", () => T = !0), document.addEventListener("resume", () => T = !1);
    const C = "runtime", W = class extends self._$DOMHandler$_ {
        #t=-1;
        constructor(t) {
            super(t, C), this._$_enableWindowResizeEvent$_ = !1, this._$_targetOrientation$_ = "any", 
            this._$_attachedDeviceOrientationEvent$_ = !1, this._$_attachedDeviceMotionEvent$_ = !1, 
            this._$_pageVisibilityIsHidden$_ = !1, this._$_isPollingGamepads$_ = !1, this._$_pollGamepadRafCallback$_ = () => this._$_OnPollGamepads$_(), 
            this._$_gamepadInputCallbacks$_ = new Set, this._$_screenReaderTextWrap$_ = document.createElement("div"), 
            this._$_screenReaderTextWrap$_.className = "c3-screen-reader-text", this._$_screenReaderTextWrap$_.setAttribute("aria-live", "polite"), 
            document.body.appendChild(this._$_screenReaderTextWrap$_), this._$_debugHighlightElem$_ = null, 
            this._$_isExportToVideo$_ = !1, this._$_exportVideoProgressMessage$_ = "", this._$_exportVideoUpdateTimerId$_ = -1, 
            this._$_enableAndroidVKDetection$_ = !1, this._$_lastWindowWidth$_ = t._$_GetWindowInnerWidth$_(), 
            this._$_lastWindowHeight$_ = t._$_GetWindowInnerHeight$_(), this._$_virtualKeyboardHeight$_ = 0, 
            this._$_vkTranslateYOffset$_ = 0, t._$AddRuntimeComponentMessageHandler$_("runtime", "invoke-download", t => this._$_OnInvokeDownload$_(t)), 
            t._$AddRuntimeComponentMessageHandler$_("runtime", "load-webfonts", t => this._$_OnLoadWebFonts$_(t)), 
            t._$AddRuntimeComponentMessageHandler$_("runtime", "raster-svg-image", t => this._$_OnRasterSvgImage$_(t)), 
            t._$AddRuntimeComponentMessageHandler$_("runtime", "get-svg-image-size", t => this._$_OnGetSvgImageSize$_(t)), 
            t._$AddRuntimeComponentMessageHandler$_("runtime", "set-target-orientation", t => this._$_OnSetTargetOrientation$_(t)), 
            t._$AddRuntimeComponentMessageHandler$_("runtime", "register-sw", () => this._$_OnRegisterSW$_()), 
            t._$AddRuntimeComponentMessageHandler$_("runtime", "post-to-debugger", t => this._$_OnPostToDebugger$_(t)), 
            t._$AddRuntimeComponentMessageHandler$_("runtime", "go-to-script", t => this._$_OnPostToDebugger$_(t)), 
            t._$AddRuntimeComponentMessageHandler$_("runtime", "before-start-ticking", () => this._$_OnBeforeStartTicking$_()), 
            t._$AddRuntimeComponentMessageHandler$_("runtime", "debug-highlight", t => this._$_OnDebugHighlight$_(t)), 
            t._$AddRuntimeComponentMessageHandler$_("runtime", "enable-device-orientation", () => this._$_AttachDeviceOrientationEvent$_()), 
            t._$AddRuntimeComponentMessageHandler$_("runtime", "enable-device-motion", () => this._$_AttachDeviceMotionEvent$_()), 
            t._$AddRuntimeComponentMessageHandler$_("runtime", "add-stylesheet", t => this._$_OnAddStylesheet$_(t)), 
            t._$AddRuntimeComponentMessageHandler$_("runtime", "script-create-worker", t => this._$_OnScriptCreateWorker$_(t)), 
            t._$AddRuntimeComponentMessageHandler$_("runtime", "alert", t => this._$_OnAlert$_(t)), 
            t._$AddRuntimeComponentMessageHandler$_("runtime", "screen-reader-text", t => this._$_OnScreenReaderTextEvent$_(t)), 
            t._$AddRuntimeComponentMessageHandler$_("runtime", "hide-cordova-splash", () => this._$_OnHideCordovaSplash$_()), 
            t._$AddRuntimeComponentMessageHandler$_("runtime", "set-exporting-to-video", t => this._$_SetExportingToVideo$_(t)), 
            t._$AddRuntimeComponentMessageHandler$_("runtime", "export-to-video-progress", t => this._$_OnExportVideoProgress$_(t)), 
            t._$AddRuntimeComponentMessageHandler$_("runtime", "exported-to-video", t => this._$_OnExportedToVideo$_(t)), 
            t._$AddRuntimeComponentMessageHandler$_("runtime", "exported-to-image-sequence", t => this._$_OnExportedToImageSequence$_(t));
            const e = new Set([ "input", "textarea", "datalist" ]);
            if (window.addEventListener("contextmenu", t => {
                const i = t.target, s = i.tagName.toLowerCase();
                e.has(s) || x(i) || t.preventDefault();
            }), window.addEventListener("selectstart", E), window.addEventListener("gesturehold", E), 
            window.addEventListener("touchstart", E, {
                passive: !1
            }), window.addEventListener("pointerdown", E, {
                passive: !1
            }), this._$_mousePointerLastButtons$_ = 0, window.addEventListener("mousedown", t => {
                1 === t.button && t.preventDefault();
            }), window.addEventListener("mousewheel", P, {
                passive: !1
            }), window.addEventListener("wheel", P, {
                passive: !1
            }), window.addEventListener("keydown", t => this.#e(t)), window.addEventListener("resize", () => this._$_OnWindowResize$_()), 
            window.addEventListener("fullscreenchange", () => this._$_OnFullscreenChange$_()), 
            window.addEventListener("webkitfullscreenchange", () => this._$_OnFullscreenChange$_()), 
            window.addEventListener("mozfullscreenchange", () => this._$_OnFullscreenChange$_()), 
            window.addEventListener("fullscreenerror", t => this._$_OnFullscreenError$_(t)), 
            window.addEventListener("webkitfullscreenerror", t => this._$_OnFullscreenError$_(t)), 
            window.addEventListener("mozfullscreenerror", t => this._$_OnFullscreenError$_(t)), 
            t._$IsiOSWebView$_()) {
                let t = 1 / 0;
                window.visualViewport.addEventListener("resize", () => {
                    const e = window.visualViewport.height;
                    e > t && (document.scrollingElement.scrollTop = 0, document.scrollingElement.scrollLeft = 0), 
                    t = e;
                }), document.documentElement.setAttribute("ioswebview", "");
            }
            this._$_mediaPendingPlay$_ = new Set, this._$_mediaRemovedPendingPlay$_ = new WeakSet, 
            this._$_isSilent$_ = !1;
        }
        _$_AddDefaultCanvasEventHandlers$_(t) {
            t.addEventListener("selectstart", E), t.addEventListener("gesturehold", E), t.addEventListener("pointerdown", E);
        }
        _$_AddDefaultHTMLWrapEventHandlers$_(t) {
            t.addEventListener("selectstart", I), t.addEventListener("gesturehold", I), t.addEventListener("touchstart", I), 
            t.addEventListener("dragstart", I);
        }
        _$_OnBeforeStartTicking$_() {
            return self.setTimeout(() => {
                this._$_enableAndroidVKDetection$_ = !0;
            }, 1e3), this._$_iRuntime$_._$IsiOSWebView$_() && this._$_OnWindowResize$_(), "cordova" === this._$_iRuntime$_._$GetExportType$_() ? (document.addEventListener("pause", () => this._$_OnVisibilityChange$_(!0)), 
            document.addEventListener("resume", () => this._$_OnVisibilityChange$_(!1))) : document.addEventListener("visibilitychange", () => this._$_OnVisibilityChange$_("hidden" === document.visibilityState)), 
            this._$_pageVisibilityIsHidden$_ = !("hidden" !== document.visibilityState && !T), 
            {
                isSuspended: this._$_pageVisibilityIsHidden$_
            };
        }
        _$Attach$_() {
            window.addEventListener("focus", () => this._$_PostRuntimeEvent$_("window-focus")), 
            window.addEventListener("blur", () => {
                this._$_PostRuntimeEvent$_("window-blur", {
                    parentHasFocus: R()
                }), this._$_mousePointerLastButtons$_ = 0;
            }), window.addEventListener("focusin", t => {
                var e;
                e = t.target, (O.has(e.tagName.toLowerCase()) || x(e)) && this._$_PostRuntimeEvent$_("keyboard-blur");
            }), window.addEventListener("keydown", t => this._$_OnKeyEvent$_("keydown", t)), 
            window.addEventListener("keyup", t => this._$_OnKeyEvent$_("keyup", t)), window.addEventListener("mousedown", t => this._$_OnMouseEvent$_("mousedown", t, k)), 
            window.addEventListener("mousemove", t => this._$_OnMouseEvent$_("mousemove", t, k)), 
            window.addEventListener("mouseup", t => this._$_OnMouseEvent$_("mouseup", t, k)), 
            window.addEventListener("dblclick", t => this._$_OnMouseEvent$_("dblclick", t, b)), 
            window.addEventListener("wheel", t => this._$_OnMouseWheelEvent$_("wheel", t, b)), 
            window.addEventListener("pointerdown", t => {
                this._$_HandlePointerDownFocus$_(t), this._$_OnPointerEvent$_("pointerdown", t);
            }), this._$_iRuntime$_._$UsesWorker$_() && void 0 !== window.onpointerrawupdate && self === self.top ? window.addEventListener("pointerrawupdate", t => this._$_OnPointerRawUpdate$_(t)) : window.addEventListener("pointermove", t => this._$_OnPointerEvent$_("pointermove", t)), 
            window.addEventListener("pointerup", t => this._$_OnPointerEvent$_("pointerup", t)), 
            window.addEventListener("pointercancel", t => this._$_OnPointerEvent$_("pointercancel", t));
            const t = () => this._$_PlayPendingMedia$_();
            window.addEventListener("pointerup", t, !0), window.addEventListener("touchend", t, !0), 
            window.addEventListener("click", t, !0), window.addEventListener("keydown", t, !0);
            try {
                navigator.getGamepads().some(t => !!t) && (this._$_iRuntime$_._$_AddRAFCallback$_(this._$_pollGamepadRafCallback$_), 
                this._$_isPollingGamepads$_ = !0);
            } catch (t) {
                console.warn("[Construct] Unable to access gamepads for starting media playback: ", t);
            }
            window.addEventListener("gamepadconnected", () => this._$_OnGamepadConnected$_(), !0), 
            window.addEventListener("gamepaddisconnected", () => this._$_OnGamepadDisconnected$_(), !0), 
            this._$_iRuntime$_._$IsAndroid$_() && !this._$_iRuntime$_._$IsAndroidWebView$_() && navigator.virtualKeyboard && (navigator.virtualKeyboard.overlaysContent = !0, 
            navigator.virtualKeyboard.addEventListener("geometrychange", () => {
                this._$_OnAndroidVirtualKeyboardChange$_(this._$_GetWindowInnerHeight$_(), navigator.virtualKeyboard.boundingRect.height);
            })), this._$_iRuntime$_._$IsiOSWebView$_() && (document.scrollingElement.scrollTop = 0, 
            document.scrollingElement.scrollLeft = 0);
        }
        _$_OnAndroidVirtualKeyboardChange$_(t, e) {
            if (document.body.style.position = "", document.body.style.overflow = "", document.body.style.transform = "", 
            this._$_vkTranslateYOffset$_ = 0, e > 0) {
                const i = document.activeElement;
                if (i) {
                    const s = i.getBoundingClientRect();
                    let n = (s.top + s.bottom) / 2 - (t - e) / 2;
                    n > e && (n = e), n < 0 && (n = 0), n > 0 && (document.body.style.position = "absolute", 
                    document.body.style.overflow = "visible", document.body.style.transform = `translateY(${-n}px)`, 
                    this._$_vkTranslateYOffset$_ = n);
                }
            }
        }
        _$_PostRuntimeEvent$_(t, e) {
            this._$PostToRuntime$_(t, e || null, S);
        }
        _$_GetWindowInnerWidth$_() {
            return this._$_iRuntime$_._$_GetWindowInnerWidth$_();
        }
        _$_GetWindowInnerHeight$_() {
            return this._$_iRuntime$_._$_GetWindowInnerHeight$_();
        }
        _$_EnableWindowResizeEvent$_() {
            this._$_enableWindowResizeEvent$_ = !0, this._$_lastWindowWidth$_ = this._$_iRuntime$_._$_GetWindowInnerWidth$_(), 
            this._$_lastWindowHeight$_ = this._$_iRuntime$_._$_GetWindowInnerHeight$_();
        }
        _$_OnWindowResize$_() {
            if (this._$_isExportToVideo$_) return;
            if (!this._$_enableWindowResizeEvent$_) return;
            const t = this._$_GetWindowInnerWidth$_(), e = this._$_GetWindowInnerHeight$_();
            if (this._$_iRuntime$_._$IsAndroidWebView$_()) if (this._$_enableAndroidVKDetection$_) {
                if (this._$_iRuntime$_._$CanDoAndroidVirtualKeyboardDetection$_() && this._$_lastWindowWidth$_ === t && e < this._$_lastWindowHeight$_) return this._$_virtualKeyboardHeight$_ = this._$_lastWindowHeight$_ - e, 
                void this._$_OnAndroidVirtualKeyboardChange$_(this._$_lastWindowHeight$_, this._$_virtualKeyboardHeight$_);
                this._$_virtualKeyboardHeight$_ > 0 && (this._$_virtualKeyboardHeight$_ = 0, this._$_OnAndroidVirtualKeyboardChange$_(e, this._$_virtualKeyboardHeight$_)), 
                this._$_lastWindowWidth$_ = t, this._$_lastWindowHeight$_ = e;
            } else this._$_lastWindowWidth$_ = t, this._$_lastWindowHeight$_ = e;
            this._$PostToRuntime$_("window-resize", {
                innerWidth: t,
                innerHeight: e,
                devicePixelRatio: window.devicePixelRatio,
                isFullscreen: v._$IsDocumentFullscreen$_(),
                cssDisplayMode: this._$_iRuntime$_._$GetCssDisplayMode$_()
            }), this._$_iRuntime$_._$IsiOSWebView$_() && this.#o(t, e, 0);
        }
        #o(t, e, i) {
            -1 !== this.#t && clearTimeout(this.#t), this.#t = setTimeout(() => this.#i(t, e, i), 100);
        }
        #i(t, e, i) {
            this.#t = -1;
            const s = this._$_GetWindowInnerWidth$_(), n = this._$_GetWindowInnerHeight$_();
            s !== t || n !== e ? this._$PostToRuntime$_("window-resize", {
                innerWidth: s,
                innerHeight: n,
                devicePixelRatio: window.devicePixelRatio,
                isFullscreen: v._$IsDocumentFullscreen$_(),
                cssDisplayMode: this._$_iRuntime$_._$GetCssDisplayMode$_()
            }) : i < 10 && this.#o(s, n, i + 1);
        }
        _$_OnSetTargetOrientation$_(t) {
            this._$_targetOrientation$_ = t.targetOrientation;
        }
        _$_TrySetTargetOrientation$_() {
            const t = this._$_targetOrientation$_;
            if (screen.orientation && screen.orientation.lock) screen.orientation.lock(t).catch(t => console.warn("[Construct] Failed to lock orientation: ", t)); else try {
                let e = !1;
                screen.lockOrientation ? e = screen.lockOrientation(t) : screen.webkitLockOrientation ? e = screen.webkitLockOrientation(t) : screen.mozLockOrientation ? e = screen.mozLockOrientation(t) : screen.msLockOrientation && (e = screen.msLockOrientation(t)), 
                e || console.warn("[Construct] Failed to lock orientation");
            } catch (t) {
                console.warn("[Construct] Failed to lock orientation: ", t);
            }
        }
        _$_OnFullscreenChange$_() {
            if (this._$_isExportToVideo$_) return;
            const t = v._$IsDocumentFullscreen$_();
            t && "any" !== this._$_targetOrientation$_ && this._$_TrySetTargetOrientation$_(), 
            this._$PostToRuntime$_("fullscreenchange", {
                isFullscreen: t,
                innerWidth: this._$_GetWindowInnerWidth$_(),
                innerHeight: this._$_GetWindowInnerHeight$_()
            });
        }
        _$_OnFullscreenError$_(t) {
            console.warn("[Construct] Fullscreen request failed: ", t), this._$PostToRuntime$_("fullscreenerror", {
                isFullscreen: v._$IsDocumentFullscreen$_(),
                innerWidth: this._$_GetWindowInnerWidth$_(),
                innerHeight: this._$_GetWindowInnerHeight$_()
            });
        }
        _$_OnVisibilityChange$_(t) {
            if (this._$_pageVisibilityIsHidden$_ !== t && (this._$_pageVisibilityIsHidden$_ = t, 
            t ? this._$_iRuntime$_._$_CancelAnimationFrame$_() : this._$_iRuntime$_._$_RequestAnimationFrame$_(), 
            this._$PostToRuntime$_("visibilitychange", {
                hidden: t
            }), !t && this._$_iRuntime$_._$IsiOSWebView$_())) {
                const t = () => {
                    document.scrollingElement.scrollTop = 0, document.scrollingElement.scrollLeft = 0;
                };
                setTimeout(t, 50), setTimeout(t, 100), setTimeout(t, 250), setTimeout(t, 500);
            }
        }
        #e(t) {
            "windows-webview2" !== this._$_iRuntime$_._$GetExportType$_() || "F3" !== t.key && "F5" !== t.key || t.preventDefault();
        }
        _$_OnKeyEvent$_(t, e) {
            if (void 0 === e.key) return;
            if ("Backspace" === e.key && E(e), this._$_isExportToVideo$_) return;
            const i = y.get(e.code) || e.code;
            this._$_PostToRuntimeMaybeSync$_(t, {
                code: i,
                key: e.key,
                which: e.which,
                repeat: e.repeat,
                altKey: e.altKey,
                ctrlKey: e.ctrlKey,
                metaKey: e.metaKey,
                shiftKey: e.shiftKey,
                timeStamp: e.timeStamp
            }, b);
        }
        _$_OnMouseWheelEvent$_(t, e, i) {
            this._$_isExportToVideo$_ || this._$PostToRuntime$_(t, {
                clientX: e.clientX,
                clientY: e.clientY + this._$_vkTranslateYOffset$_,
                pageX: e.pageX,
                pageY: e.pageY + this._$_vkTranslateYOffset$_,
                deltaX: e.deltaX,
                deltaY: e.deltaY,
                deltaZ: e.deltaZ,
                deltaMode: e.deltaMode,
                timeStamp: e.timeStamp
            }, i);
        }
        _$_OnMouseEvent$_(t, e, i) {
            this._$_isExportToVideo$_ || g(e) || this._$_PostToRuntimeMaybeSync$_(t, {
                button: e.button,
                buttons: e.buttons,
                clientX: e.clientX,
                clientY: e.clientY + this._$_vkTranslateYOffset$_,
                pageX: e.pageX,
                pageY: e.pageY + this._$_vkTranslateYOffset$_,
                movementX: e.movementX || 0,
                movementY: e.movementY || 0,
                timeStamp: e.timeStamp
            }, i);
        }
        _$_OnPointerEvent$_(t, e) {
            if (this._$_isExportToVideo$_) return;
            let i = 0;
            "mouse" === e.pointerType && (i = this._$_mousePointerLastButtons$_), this._$_PostToRuntimeMaybeSync$_(t, {
                pointerId: e.pointerId,
                pointerType: e.pointerType,
                button: e.button,
                buttons: e.buttons,
                lastButtons: i,
                clientX: e.clientX,
                clientY: e.clientY + this._$_vkTranslateYOffset$_,
                pageX: e.pageX,
                pageY: e.pageY + this._$_vkTranslateYOffset$_,
                movementX: e.movementX || 0,
                movementY: e.movementY || 0,
                width: e.width || 0,
                height: e.height || 0,
                pressure: e.pressure || 0,
                tangentialPressure: e.tangentialPressure || 0,
                tiltX: e.tiltX || 0,
                tiltY: e.tiltY || 0,
                twist: e.twist || 0,
                timeStamp: e.timeStamp
            }, b), "mouse" === e.pointerType && (this._$_mousePointerLastButtons$_ = e.buttons);
        }
        _$_OnPointerRawUpdate$_(t) {
            this._$_OnPointerEvent$_("pointermove", t);
        }
        _$_OnTouchEvent$_(t, e) {
            if (!this._$_isExportToVideo$_) for (let i = 0, s = e.changedTouches.length; i < s; ++i) {
                const s = e.changedTouches[i];
                this._$_PostToRuntimeMaybeSync$_(t, {
                    pointerId: s.identifier,
                    pointerType: "touch",
                    button: 0,
                    buttons: 0,
                    lastButtons: 0,
                    clientX: s.clientX,
                    clientY: s.clientY + this._$_vkTranslateYOffset$_,
                    pageX: s.pageX,
                    pageY: s.pageY + this._$_vkTranslateYOffset$_,
                    movementX: e.movementX || 0,
                    movementY: e.movementY || 0,
                    width: 2 * (s.radiusX || s.webkitRadiusX || 0),
                    height: 2 * (s.radiusY || s.webkitRadiusY || 0),
                    pressure: s.force || s.webkitForce || 0,
                    tangentialPressure: 0,
                    tiltX: 0,
                    tiltY: 0,
                    twist: s.rotationAngle || 0,
                    timeStamp: e.timeStamp
                }, b);
            }
        }
        _$_HandlePointerDownFocus$_(t) {
            window !== window.top && window.focus(), this._$_IsElementCanvasOrDocument$_(t.target) && document.activeElement && !this._$_IsElementCanvasOrDocument$_(document.activeElement) && document.activeElement.blur();
        }
        _$_IsElementCanvasOrDocument$_(t) {
            return !t || t === document || t === window || t === document.body || "canvas" === t.tagName.toLowerCase();
        }
        _$_AttachDeviceOrientationEvent$_() {
            this._$_attachedDeviceOrientationEvent$_ || (this._$_attachedDeviceOrientationEvent$_ = !0, 
            window.addEventListener("deviceorientation", t => this._$_OnDeviceOrientation$_(t)), 
            window.addEventListener("deviceorientationabsolute", t => this._$_OnDeviceOrientationAbsolute$_(t)));
        }
        _$_AttachDeviceMotionEvent$_() {
            this._$_attachedDeviceMotionEvent$_ || (this._$_attachedDeviceMotionEvent$_ = !0, 
            window.addEventListener("devicemotion", t => this._$_OnDeviceMotion$_(t)));
        }
        _$_OnDeviceOrientation$_(t) {
            this._$_isExportToVideo$_ || this._$PostToRuntime$_("deviceorientation", {
                absolute: !!t.absolute,
                alpha: t.alpha || 0,
                beta: t.beta || 0,
                gamma: t.gamma || 0,
                timeStamp: t.timeStamp,
                webkitCompassHeading: t.webkitCompassHeading,
                webkitCompassAccuracy: t.webkitCompassAccuracy
            }, b);
        }
        _$_OnDeviceOrientationAbsolute$_(t) {
            this._$_isExportToVideo$_ || this._$PostToRuntime$_("deviceorientationabsolute", {
                absolute: !!t.absolute,
                alpha: t.alpha || 0,
                beta: t.beta || 0,
                gamma: t.gamma || 0,
                timeStamp: t.timeStamp
            }, b);
        }
        _$_OnDeviceMotion$_(t) {
            if (this._$_isExportToVideo$_) return;
            let e = null;
            const i = t.acceleration;
            i && (e = {
                x: i.x || 0,
                y: i.y || 0,
                z: i.z || 0
            });
            let s = null;
            const n = t.accelerationIncludingGravity;
            n && (s = {
                x: n.x || 0,
                y: n.y || 0,
                z: n.z || 0
            });
            let o = null;
            const r = t.rotationRate;
            r && (o = {
                alpha: r.alpha || 0,
                beta: r.beta || 0,
                gamma: r.gamma || 0
            }), this._$PostToRuntime$_("devicemotion", {
                acceleration: e,
                accelerationIncludingGravity: s,
                rotationRate: o,
                interval: t.interval,
                timeStamp: t.timeStamp
            }, b);
        }
        _$_OnInvokeDownload$_(t) {
            const e = t.url, i = t.filename, s = document.createElement("a"), n = document.body;
            s.textContent = i, s.href = e, s.download = i, n.appendChild(s), s.click(), n.removeChild(s);
        }
        async _$_OnLoadWebFonts$_(t) {
            const e = t.webfonts;
            await Promise.all(e.map(async t => {
                const e = new FontFace(t.name, `url('${t.url}')`);
                document.fonts.add(e), await e.load();
            }));
        }
        async _$_OnRasterSvgImage$_(t) {
            const e = t.blob, i = t.imageWidth, s = t.imageHeight, n = t.surfaceWidth, o = t.surfaceHeight, r = t.imageBitmapOpts, a = await self.C3_RasterSvgImageBlob(e, i, s, n, o);
            let h;
            return h = r ? await createImageBitmap(a, r) : await createImageBitmap(a), {
                imageBitmap: h,
                transferables: [ h ]
            };
        }
        async _$_OnGetSvgImageSize$_(t) {
            return await self.C3_GetSvgImageSize(t.blob);
        }
        async _$_OnAddStylesheet$_(t) {
            var e;
            await (e = t.url, new Promise((t, i) => {
                const s = document.createElement("link");
                s.onload = () => t(s), s.onerror = t => i(t), s.rel = "stylesheet", s.href = e, 
                document.head.appendChild(s);
            }));
        }
        _$_PlayPendingMedia$_() {
            const t = [ ...this._$_mediaPendingPlay$_ ];
            if (this._$_mediaPendingPlay$_.clear(), !this._$_isSilent$_) for (const e of t) {
                const t = e.play();
                t && t.catch(t => {
                    this._$_mediaRemovedPendingPlay$_.has(e) || this._$_mediaPendingPlay$_.add(e);
                });
            }
        }
        _$TryPlayMedia$_(t) {
            if ("function" != typeof t.play) throw new Error("missing play function");
            let e;
            this._$_mediaRemovedPendingPlay$_.delete(t);
            try {
                e = t.play();
            } catch (e) {
                return void this._$_mediaPendingPlay$_.add(t);
            }
            e && e.catch(e => {
                this._$_mediaRemovedPendingPlay$_.has(t) || this._$_mediaPendingPlay$_.add(t);
            });
        }
        _$RemovePendingPlay$_(t) {
            this._$_mediaPendingPlay$_.delete(t), this._$_mediaRemovedPendingPlay$_.add(t);
        }
        _$SetSilent$_(t) {
            this._$_isSilent$_ = !!t;
        }
        _$_OnGamepadConnected$_() {
            this._$_isPollingGamepads$_ || (this._$_iRuntime$_._$_AddRAFCallback$_(this._$_pollGamepadRafCallback$_), 
            this._$_isPollingGamepads$_ = !0, this._$_OnAnyGamepadInput$_());
        }
        _$_OnGamepadDisconnected$_() {
            this._$_isPollingGamepads$_ && navigator.getGamepads().every(t => !t) && (this._$_iRuntime$_._$_RemoveRAFCallback$_(this._$_pollGamepadRafCallback$_), 
            this._$_isPollingGamepads$_ = !1);
        }
        _$_OnPollGamepads$_() {
            navigator.getGamepads().some(t => t && t.buttons.some(t => t.pressed)) && this._$_OnAnyGamepadInput$_();
        }
        _$_OnAnyGamepadInput$_() {
            this._$_PlayPendingMedia$_();
            for (const t of this._$_gamepadInputCallbacks$_) t();
        }
        _$_AddAnyGamepadInputCallback$_(t) {
            this._$_gamepadInputCallbacks$_.add(t);
        }
        _$_RemoveAnyGamepadInputCallback$_(t) {
            this._$_gamepadInputCallbacks$_.delete(t);
        }
        _$_OnHideCordovaSplash$_() {
            navigator.splashscreen && navigator.splashscreen.hide && navigator.splashscreen.hide();
        }
        _$_OnDebugHighlight$_(t) {
            if (!t.show) return void (this._$_debugHighlightElem$_ && (this._$_debugHighlightElem$_.style.display = "none"));
            this._$_debugHighlightElem$_ || (this._$_debugHighlightElem$_ = document.createElement("div"), 
            this._$_debugHighlightElem$_.id = "inspectOutline", document.body.appendChild(this._$_debugHighlightElem$_));
            const e = this._$_debugHighlightElem$_;
            e.style.display = "", e.style.left = t.left - 1 + "px", e.style.top = t.top - 1 + "px", 
            e.style.width = t.width + 2 + "px", e.style.height = t.height + 2 + "px", e.textContent = t.name;
        }
        _$_OnRegisterSW$_() {
            window.C3_RegisterSW && window.C3_RegisterSW();
        }
        _$_OnPostToDebugger$_(t) {
            window.c3_postToMessagePort && (t.from = "runtime", window.c3_postToMessagePort(t));
        }
        _$_InvokeFunctionFromJS$_(t, e) {
            return this._$PostToRuntimeAsync$_("js-invoke-function", {
                name: t,
                params: e
            });
        }
        _$_OnScriptCreateWorker$_(t) {
            const e = t.url, i = t.opts, s = t.port2;
            new Worker(e, i).postMessage({
                type: "construct-worker-init",
                port2: s
            }, [ s ]);
        }
        _$_OnAlert$_(t) {
            alert(t.message);
        }
        _$_OnScreenReaderTextEvent$_(t) {
            const e = t.type;
            if ("create" === e) {
                const e = document.createElement("p");
                e.id = "c3-sr-" + t.id, e.textContent = t.text, this._$_screenReaderTextWrap$_.appendChild(e);
            } else if ("update" === e) {
                const e = document.getElementById("c3-sr-" + t.id);
                e ? e.textContent = t.text : console.warn(`[Construct] Missing screen reader text with id ${t.id}`);
            } else if ("release" === e) {
                const e = document.getElementById("c3-sr-" + t.id);
                e ? e.remove() : console.warn(`[Construct] Missing screen reader text with id ${t.id}`);
            } else console.warn(`[Construct] Unknown screen reader text update '${e}'`);
        }
        _$_SetExportingToVideo$_(t) {
            this._$_isExportToVideo$_ = !0;
            const e = document.createElement("h1");
            e.id = "exportToVideoMessage", e.textContent = t.message, document.body.prepend(e), 
            document.body.classList.add("exportingToVideo"), this._$GetRuntimeInterface$_()._$GetMainCanvas$_().style.display = "", 
            this._$_iRuntime$_._$SetIsExportingToVideo$_(t.duration);
        }
        _$_OnExportVideoProgress$_(t) {
            this._$_exportVideoProgressMessage$_ = t.message, -1 === this._$_exportVideoUpdateTimerId$_ && (this._$_exportVideoUpdateTimerId$_ = setTimeout(() => this._$_DoUpdateExportVideoProgressMessage$_(), 250));
        }
        _$_DoUpdateExportVideoProgressMessage$_() {
            this._$_exportVideoUpdateTimerId$_ = -1;
            const t = document.getElementById("exportToVideoMessage");
            t && (t.textContent = this._$_exportVideoProgressMessage$_);
        }
        _$_OnExportedToVideo$_(t) {
            window._$c3_postToMessagePort$_({
                type: "exported-video",
                arrayBuffer: t.arrayBuffer,
                contentType: t.contentType,
                time: t.time
            });
        }
        _$_OnExportedToImageSequence$_(t) {
            window._$c3_postToMessagePort$_({
                type: "exported-image-sequence",
                blobArr: t.blobArr,
                time: t.time,
                gif: t.gif
            });
        }
    };
    v._$AddDOMHandlerClass$_(W);
}

{
    const A = "dispatchworker.js", F = "jobworker.js";
    self._$JobSchedulerDOM$_ = class {
        constructor(t) {
            this._$_runtimeInterface$_ = t, this._$_maxNumWorkers$_ = Math.min(navigator.hardwareConcurrency || 2, 16), 
            this._$_dispatchWorker$_ = null, this._$_jobWorkers$_ = [], this._$_inputPort$_ = null, 
            this._$_outputPort$_ = null;
        }
        async _$Init$_() {
            if (this._$_hasInitialised$_) throw new Error("already initialised");
            this._$_hasInitialised$_ = !0;
            const t = this._$_runtimeInterface$_._$GetScriptFolder$_() + A;
            this._$_dispatchWorker$_ = await this._$_runtimeInterface$_._$CreateWorker$_(t, {
                name: "DispatchWorker"
            });
            const e = new MessageChannel;
            this._$_inputPort$_ = e.port1, this._$_dispatchWorker$_.postMessage({
                type: "_init",
                "in-port": e.port2
            }, [ e.port2 ]), this._$_outputPort$_ = await this._$_CreateJobWorker$_();
        }
        async _$_CreateJobWorker$_() {
            const t = this._$_jobWorkers$_.length, e = this._$_runtimeInterface$_._$GetScriptFolder$_() + F, i = await this._$_runtimeInterface$_._$CreateWorker$_(e, {
                name: "JobWorker" + t
            }), s = new MessageChannel, n = new MessageChannel;
            return this._$_dispatchWorker$_.postMessage({
                type: "_addJobWorker",
                port: s.port1
            }, [ s.port1 ]), i.postMessage({
                type: "init",
                number: t,
                "dispatch-port": s.port2,
                "output-port": n.port2
            }, [ s.port2, n.port2 ]), this._$_jobWorkers$_.push(i), n.port1;
        }
        _$GetPortData$_() {
            return {
                inputPort: this._$_inputPort$_,
                outputPort: this._$_outputPort$_,
                maxNumWorkers: this._$_maxNumWorkers$_
            };
        }
        _$GetPortTransferables$_() {
            return [ this._$_inputPort$_, this._$_outputPort$_ ];
        }
    };
}

{
    const D = "keyboard", H = class extends self._$DOMHandler$_ {
        constructor(t) {
            super(t, D), this._$_isKeyboardLockSupported$_ = !(!navigator.keyboard || !navigator.keyboard.lock), 
            this._$AddRuntimeMessageHandlers$_([ [ "init", () => this._$_OnInit$_() ], [ "lock-keyboard", t => this._$_OnLockKeyboard$_(t) ], [ "unlock-keyboard", () => this._$_OnUnlockKeyboard$_() ] ]);
        }
        _$_OnInit$_() {
            return {
                isKeyboardLockSupported: this._$_isKeyboardLockSupported$_
            };
        }
        async _$_OnLockKeyboard$_(t) {
            const e = t.keysArr;
            try {
                return 0 === e.length ? await navigator.keyboard.lock() : await navigator.keyboard.lock(e), 
                {
                    isOk: !0
                };
            } catch (t) {
                return console.error("Error locking keyboard:", t), {
                    isOk: !1
                };
            }
        }
        _$_OnUnlockKeyboard$_() {
            try {
                navigator.keyboard.unlock();
            } catch (t) {
                console.error("Error unlocking keyboard:", t);
            }
        }
    };
    self._$RuntimeInterface$_._$AddDOMHandlerClass$_(H);
}

{
    const L = "mouse", U = class extends self._$DOMHandler$_ {
        #t=!1;
        #e=!1;
        #a="";
        constructor(t) {
            super(t, L), this._$AddRuntimeMessageHandlers$_([ [ "init", t => this.#n(t) ], [ "cursor", t => this.#i(t) ], [ "request-pointer-lock", t => this.#o(t) ], [ "release-pointer-lock", () => this.#s() ] ]), 
            document.addEventListener("pointerlockchange", t => this.#h()), document.addEventListener("pointerlockerror", t => this.#r());
        }
        #n(t) {
            this.#t = t.isPointerLockWrapperPolyfill, this.#t && (this._$_iRuntime$_._$_AddWrapperMessageHandler$_("set-pointer-lock-enabled-response", t => this.#l(t)), 
            this._$_iRuntime$_._$_AddWrapperMessageHandler$_("pointer-lock-movement", t => this.#d(t)), 
            window.addEventListener("blur", () => this.#u()));
        }
        #i(t) {
            this.#a = t, "linux-cef" === this._$_iRuntime$_._$GetExportType$_() && this.#e || (document.documentElement.style.cursor = t);
        }
        #o(t) {
            this.#t ? ("linux-cef" === this._$_iRuntime$_._$GetExportType$_() && (this.#e = !0, 
            document.documentElement.style.cursor = "none"), this._$_iRuntime$_._$_SendWrapperMessage$_({
                type: "set-pointer-lock-enabled",
                isEnabled: !0
            })) : this._$_iRuntime$_._$GetMainCanvas$_().requestPointerLock(t);
        }
        #s() {
            this.#t ? this._$_iRuntime$_._$_SendWrapperMessage$_({
                type: "set-pointer-lock-enabled",
                isEnabled: !1
            }) : document.exitPointerLock();
        }
        #h() {
            this._$PostToRuntime$_("pointer-lock-change", {
                hasPointerLock: !!document.pointerLockElement
            });
        }
        #r() {
            this._$PostToRuntime$_("pointer-lock-error", {
                hasPointerLock: !!document.pointerLockElement
            });
        }
        #l(t) {
            t.isOk ? (this.#e = t.isEnabled, this._$PostToRuntime$_("pointer-lock-change", {
                hasPointerLock: t.isEnabled
            })) : (console.error(`[Mouse] Unable to obtain pointer lock (via wrapper): error ${t.error}`), 
            this.#e = !1, this._$PostToRuntime$_("pointer-lock-error", {
                hasPointerLock: !1
            })), "linux-cef" !== this._$_iRuntime$_._$GetExportType$_() || this.#e || (document.documentElement.style.cursor = this.#a);
        }
        #d(t) {
            this._$PostToRuntime$_("wrapper-pointer-lock-movement", {
                movementX: t.movementX,
                movementY: t.movementY
            });
        }
        #u() {
            this.#s();
        }
    };
    self._$RuntimeInterface$_._$AddDOMHandlerClass$_(U);
}

if (window.C3_IsSupported) {
    const G = !0;
    window.c3_runtimeInterface = new self._$RuntimeInterface$_({
        _$useWorker$_: G,
        _$workerMainUrl$_: "workermain.js",
        _$runtimeMainScript$_: "scripts/c3main.js",
        _$scriptFolder$_: "scripts/",
        _$exportType$_: "html5"
    });
}